import React from 'react';

export const item = [
    {
        url : "#", 
        img : "button.jpg",
        alt : "thumnail image",
        brand : "버튼나인",
        title : "(후기인증)오리지널 크롭 반팔티(5color)_버튼나인",
        sale: "",
        price: "9,100",
        costPrice: "",
        purchase: "5,170개 구매중",
        no : "1",
        score : "4.5"},
    {
        url : "#", 
        img : "abigle.jpg",
        alt : "thumnail image",
        brand : "에이비글",
        title : "DEDICATION 핏 보장 루즈핏 MTM 간절기 배색 루즈핏 긴팔 Top_에이비글",
        sale: "10%",
        price: "13,230",
        costPrice: "14,700",
        purchase: "868개 구매중",
        no : "2",
        score : "4.7"},

    { 
        url : "#", 
        img : "abekjoy.jpg",
        alt : "thumnail image",
        brand : "아베크조이",
        title : "고퀄 울80 여성 골지 반목 반폴라 버튼 단추 사선 니트 티셔츠 가을 겨울 봄 162",
        sale: "5%",
        price: "46,360",
        costPrice: "48,800",
        purchase: "198개 구매중",
        no : "3",
        score : "4.3"},

    { 
        url : "#", 
        img : "daliyhere.jpg",
        alt : "thumnail image",
        brand : "데일리히어",
        title : "[6COLOR] 쫀쫀 세미크롭 라운드 반팔 티셔츠_데일리히어",
        sale: "",
        price: "9,800",
        costPrice: "",
        purchase: "3,904개 구매중",
        no : "4",
        score : "4.4"},

    { 
        url : "#", 
        img : "daybjue.jpg",
        alt : "thumnail image",
        brand : "데이비쥬",
        title : "쏘핫 U넥 쫀쫀 크롭티 (4 color) _데이비쥬",
        sale: "",
        price: "9,800",
        costPrice: "",
        purchase: "756개 구매중",
        no : "5",
        score : "4.6"},

    { 
        url : "#", 
        img : "dearmov.jpg",
        alt : "thumnail image",
        brand : "디어모브",
        title : "ggomo 오버핏 꽈배기 케이블 울 라운드 니트_디어모브",
        sale: "10%",
        price: "32,400",
        costPrice: "36,000",
        purchase: "108개 구매중",
        no : "6",
        score : "4.7"},

    { 
        url : "#", 
        img : "daon.jpg",
        alt : "thumnail image",
        brand : "다온샵",
        title : "(f.w버전) 빅사이즈/속기모/만족감100% 따뜻!!롱한핏감 구김적은 고급폴리소재!!",
        sale: "10%",
        price: "14,310",
        costPrice: "15,900",
        purchase: "",
        no : "7",
        score : "4.5"},
    { 
        url : "#", 
        img : "wonderwonder.jpg",
        alt : "thumnail image",
        brand : "원더원더",
        title : "[1+1 특가!] 크롭 미니 쫀쫀 반팔 티셔츠",
        sale: "",
        price: "7,400",
        costPrice: "",
        purchase: "1,323개 구매중",
        no : "8",
        score : "4.6"},
    { 
        url : "#", 
        img : "themuse.jpg",
        alt : "thumnail image",
        brand : "더뮤즈",
        title : "[국내생산]데일리 루즈 크롭 긴팔 4컬러_더뮤즈",
        sale: "",
        price: "9,900",
        costPrice: "",
        purchase: "631개 구매중",
        no : "9",
        score : "4.8"},
    { 
        url : "#", 
        img : "berkerming27.jpg",
        alt : "thumnail image",
        brand : "비커밍27",
        title : "V 넥 플라워 롱 원피스 _비커밍27",
        sale: "10%",
        price: "20,660",
        costPrice: "22,950",
        purchase: "454개 구매중",
        no : "10",
        score : "4.7"},
    { 
        url : "#", 
        img : "heylady.jpg",
        alt : "thumnail image",
        brand : "헤이레이디",
        title : "[내추럴♥여유핏NT]알레즈 라운드 니트",
        sale: "11%",
        price: "13,260",
        costPrice: "14,900",
        purchase: "3,378개 구매중",
        no : "11",
        score : "4.8"},
    { 
        url : "#", 
        img : "byyoung.jpg",
        alt : "thumnail image",
        brand : "바이영",
        title : "(국내제작 울60) 쓰리버튼 루즈핏 베이직 울자켓 / 자켓_바이영",
        sale: "11%",
        price: "40,940",
        costPrice: "46,000",
        purchase: "260개 구매중",
        no : "12",
        score : "4.7"},
    { 
        url : "#", 
        img : "hyonabuly.jpg",
        alt : "thumnail image",
        brand : "혀나블리",
        title : "여성스러운 무드의 크롭 브이넥니트_혀나블리",
        sale: "",
        price: "16,700",
        costPrice: "",
        purchase: "1,441개 구매중",
        no : "13",
        score : "4.6"},
    { 
        url : "#", 
        img : "donkey.jpg",
        alt : "thumnail image",
        brand : "돈키",
        title : "[브랜드핫템] sepium bag - D1032 (12color)",
        sale: "20%",
        price: "41,300",
        costPrice: "59,000",
        purchase: "1,441개 구매중",
        no : "14",
        score : "4.7"},
    { 
        url : "#", 
        img : "wansmall.jpg",
        alt : "thumnail image",
        brand : "완스몰",
        title : "[주문폭주] [오늘출발] 모먼트 브이넥 가디건",
        sale: "60%",
        price: "19,960",
        costPrice: "49,900",
        purchase: "10,852개 구매중",
        no : "15",
        score : "4.8"},
    { 
        url : "#", 
        img : "itshowj.jpg",
        alt : "thumnail image",
        brand : "잇쇼제이",
        title : "[롱한기장감] 하이 롱 세미와이드 데님 팬츠_잇쇼제이",
        sale: "11%",
        price: "28,480",
        costPrice: "32,900",
        purchase: "2,084개 구매중",
        no : "16",
        score : "4.7"},
    { 
        url : "#", 
        img : "giftybox.jpg",
        alt : "thumnail image",
        brand : "기프티박스",
        title : "[무려~울20함유!!] 요플래 와플 스퀘어넥 퍼프 니트",
        sale: "10%",
        price: "22,410",
        costPrice: "24,900",
        purchase: "32개 구매중",
        no : "17",
        score : "4.4"},
    { 
        url : "#", 
        img : "envylook.jpg",
        alt : "thumnail image",
        brand : "엔비룩",
        title : "[추천★] 삐삐와이드밴딩팬츠/기모팬츠/겨울팬츠",
        sale: "36%",
        price: "11,460",
        costPrice: "17,900",
        purchase: "3,672개 구매중",
        no : "18",
        score : "4.6"},
    { 
        url : "#", 
        img : "mosmudy.jpg",
        alt : "thumnail image",
        brand : "모디무스",
        title : "삭스 스판 스웨이드 롱 부츠 [2color]_모디무드",
        sale: "11%",
        price: "37,290",
        costPrice: "41,900",
        purchase: "213개 구매중",
        no : "19",
        score : "4.6"},
    { 
        url : "#", 
        img : "candygrow.jpg",
        alt : "thumnail image",
        brand : "캔디글로우",
        title : "[주말만 깜짝쿠폰][데일리로 딱이야! 컬러가 예쁜 라운드 니트 ] 소프트 니트",
        sale: "110",
        price: "30,600",
        costPrice: "34,000",
        purchase: "197개 구매중",
        no : "20",
        score : "4.6"}
]

// export const item = [{1:1},{1:2},{1:3},{1:4}]