export const banners = [
    { img: "banner01.png" },
    { img: "banner02.png" },
    { img: "banner03.png" },
    { img: "banner04.png" },
    { img: "banner05.png" },
    { img: "banner06.png" },
    { img: "banner07.png" },
    { img: "banner08.png" },
    { img: "banner09.png" },
    { img: "banner10.png" },
    { img: "banner11.png" },
    { img: "banner12.png" },
    { img: "banner13.png" },
    { img: "banner14.png" },
    { img: "banner15.png" },
    { img: "banner16.png" },
    { img: "banner17.png" },
    { img: "banner18.png" },
    { img: "banner19.png" },
    { img: "banner20.png" },
    { img: "banner21.png" },
]