export const banners = [
    { img: "banner1.png" },
    { img: "banner2.png" },
    { img: "banner3.png" },
    { img: "banner4.png" },
    { img: "banner5.png" },
    { img: "banner6.png" },
    { img: "banner7.png" },
    { img: "banner8.png" },
    { img: "banner9.png" },
    { img: "banner10.png" },
    { img: "banner11.png" },
    { img: "banner12.png" },
    { img: "banner13.png" },
    { img: "banner14.png" },
    { img: "banner15.png" },
    { img: "banner16.png" },
    { img: "banner17.png" },
    { img: "banner18.png" },
    { img: "banner19.png" },
    { img: "banner20.png" },
    { img: "banner21.png" },
]